env:
  global:
  - GCP_PROJECT_ID=konte-project
  - tf_version=0.14.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  export TF_VAR_project_id=$GCP_PROJECT_ID
  export TF_VAR_machinetype=$TF_ENV_machine_type
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
dd:
  secure: 5BIj4t7BRhajh0HT/z9YQ7VjTZKQKDc0WygN20eE5oDuBvz0y5V2milIm3apkA4LGopgfn8JDQQjnHdzwe90XOjSDcmLAhaiPZjDbXByfwdGrixPhWZitLm8Ml4UY44EEko/HdmLWYJwkMafNpHfyAp23wrMdsAxcxMtT/1O6WNPwdTGwfpHrIMItfqM3uSEUR9uBc6/cPO9VJFlfta2dbj4Sq1uObM4RYWrIExhLN8raa0fuu1F6dRaDpr7k38ER0Cw0ZUXR161tp9XJuokOtShDjnUH58y0dBdto3Hp5G/3cfpeOQmqSQa9pW7DXFxWMWqVD9M37AXl3WymxKymHdfHiBrKZL5dJgNde/6vlSblNOePWfR9rmsCWay/GiqYiITjAMFDZ789wEYJrf1yB6x6zT2hh/dDaGOUIn6lIg+wY6IFH7OX4sGgqKIUNBKZw3EGDJMmxtRYYXUgXVH4iT1DeOHBdTRAIphoko9dnyxndcg3mBgeLiB/c5G2Vj4sn+8Kyhv+IlCA+EHkmFYQe25B/AOZG0B4RzDX8i7JHzYobklGk550eNCVjPki5TDFwLHMJuIt0QV8gi3GQ47CQcgnOyN8VPQmJkb1SAFee04bQSo0axHNQ7ZqpPTQ01ldHPsi2CciZ0klib7pN5ig1qFVCJcl+ME22gWYtJrLT0=
